name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_SECRET }}" | docker login ghcr.oi -u ${{ github.actor }} --password-stdin

      - name: Build docker image and tag it
        run: docker build . --tag ghcr.io/${{ github.repository }}:latest

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository }}:latest